version: '3.1'
services:
  app:
    container_name: springboot-postgresql
    image: postgres
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=employeedb
      - POSTGRES_HOST_AUTH_METHOD=trust